kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-preprod
  namespace: preprod
spec:
  storageClassName: pv-preprod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
