apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-preprod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-preprod
  hostPath:
    path: /mnt/data/preprod